---
title: "Riddler Express Solution: How Many More Palindrome Dates Will You See?"
author: "Quoc Tran"
date: "02/07/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### [Riddler Express](https://fivethirtyeight.com/features/how-many-more-palindrome-dates-will-you-see/)

#### By Zach Wissner-Gross

From James Anderson comes a palindromic puzzle of calendars:

This past Sunday was Groundhog Day. Also, there was a [football game](https://www.espn.com/nfl/recap?gameId=401131047). But to top it all off, the date, 02/02/2020, was palindromic, meaning it reads the same forwards and backwards (if you ignore the slashes).

If we write out dates in the American format of MM/DD/YYYY (i.e., the two digits of the month, followed by the two digits of the day, followed by the four digits of the year), how many more palindromic dates will there be this century?

***

## My Solution

This century goes until $12/31/2099$ (maybe it includes 2100 but it doesn't matter). The year will always take the format of $20YY$, so on palindromic dates, the day must always be the second of the month. $MM/02/20YY$.

Every year where the last two digits of the year can be reversed to form a month (i.e. any ending with a $0$ or $21$ or $11$) will have one and only one palindromic date.

After Sunday's palindromic date, there are $80$ years left in the century. In these $80$ years, there are $7$ years that end with a $0$ ($2030$, $2040$, $2050$, $2060$, $2070$, $2080$, $2090$) and one that ends with $21$ (next year!).

There are $8$ remaining palindromic dates left in this century:

$12/02/2021$

$03/02/2030$

$04/02/2040$

$05/02/2050$

$06/02/2060$

$07/02/2070$

$08/02/2080$

$09/02/2090$